# _config.yml - Jekyll configuration
title: "Alkebulan - D&D World"
description: "A dark fantasy continent recovering from magical apocalypse"
baseurl: "/alkebulan-wiki" # Your repository name
url: "https://cowcow2831.github.io" # Your GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Include the pages directory
include:
  - pages

# Collections - remove this as we're using regular pages
# collections:
#   pages:
#     output: true
#     permalink: /:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Port Zephyr"
    url: "/port-zephyr/"
  - title: "Harbor District"
    url: "/harbor-district/"
  - title: "Player Handout"
    url: "/player-handout-whispers-of-the-wastes/"

# Exclude files from processing
exclude:
  - node_modules/
  - obsidian-notes/
  - convert.js
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Defaults for pages
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"

# Custom variables
author: "Your Name"
campaign: "Whispers of the Wastes"
