# _config.yml - Jekyll configuration with multi-view support
title: "Alkebulan"
description: "A dark fantasy continent recovering from magical apocalypse"
baseurl: "/alkebulan-wiki" # Your repository name
url: "https://cowcow2831.github.io" # Your GitHub Pages URL

# Player view configuration (can be overridden)
player_baseurl: "/alkebulan-wiki"
player_url: "https://cowcow2831.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Include the pages directory
include:
  - pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation - will be filtered based on view mode
navigation:
  - title: "Home"
    url: "/"
    access_level: "public"
  - title: "Port Zephyr"
    url: "/port-zephyr/"
    access_level: "public"
  - title: "Harbor District"
    url: "/harbor-district/"
    access_level: "player"
  - title: "Player Handout"
    url: "/player-handout-whispers-of-the-wastes/"
    access_level: "player"
  - title: "DM Notes"
    url: "/dm-notes/"
    access_level: "dm"
  - title: "Secrets"
    url: "/secrets/"
    access_level: "dm"

# Exclude files from processing
exclude:
  - node_modules/
  - obsidian-notes/
  - convert.js
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .github/

# Defaults for pages
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Custom variables
author: "Robert McCowan"
campaign: "Alkebulan"

# View-specific settings (will be set by build process)
view_mode: "dm" # Default to DM view
is_player_view: false
is_dm_view: true

# Access level definitions
access_levels:
  public: "Available to everyone"
  player: "Player-safe content"
  dm: "DM-only content"
  secret: "Hidden from all builds"
